# AUTOGENERATED! DO NOT EDIT! File to edit: app.ipynb.

# %% auto 0
__all__ = ['learn_inf', 'categories', 'image', 'label', 'examples', 'intf', 'classify_images']

# %% app.ipynb 23
from fastai.vision.all import *
import gradio as gr

# %% app.ipynb 25
learn_inf = load_learner('model.pkl')

# %% app.ipynb 28
categories = ('edvard_munch', 'vincent_van_gogh')

def classify_images(img):
    pred, idx,probs = learn_inf.predict(img)
    return dict(zip(categories, map(float,probs)))

# %% app.ipynb 30

title = "vincent_or_edvard"
image = gr.inputs.Image(shape=(256,256))
label = gr.outputs.Label()
examples = ['vincent_van_gogh.jpg', 'edvard_munch.jpg']

intf = gr.Interface(fn= classify_images, inputs=image, outputs=label, examples=examples)
intf.launch(inline=False)
